Backend_Project_Amado/Controllers/ShopController.cs
using Backend_Project_Amado.Data;
using Backend_Project_Amado.Entities;
using Backend_Project_Amado.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Backend_Project_Amado.Controllers
{
    public class ShopController : Controller
    {
        private AppDbContext _dbContext;

        public ShopController(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }
        public IActionResult Index(int page, string category = "Chairs", int view = 4, string order = "desc")
        {
            if (page <= 1) page = 1;
            int ProductsPerPage = view;

            int startPoint = 1;
            int endPoint = view;

            if(page > 1)
            {
                startPoint = (page - 1) * view;
                endPoint = page * view;
            }

            string categoryName = category;

            var filtered = _dbContext.Products.FirstOrDefault(x => x.Category.Name == categoryName);

            var productCount = _dbContext.Products.Count();
            var totalPageCount = (int)Math.Ceiling((decimal)productCount / ProductsPerPage);

            var products = order switch
            {
                "desc" => _dbContext.Products.OrderByDescending(x => x.Id),
                "asc" => _dbContext.Products.OrderBy(x => x.Id),
                _ => _dbContext.Products.OrderByDescending(x => x.Id)
            };

            var categories = _dbContext.Categories.AsNoTracking().ToList();
            var brands = _dbContext.Brands.AsNoTracking().ToList();
            var colors = _dbContext.Colors.AsNoTracking().ToList();

            var model = new ShopIndexVM
            {
                Products = products
                .Skip((page - 1) * ProductsPerPage)
                .Take(ProductsPerPage)
                .ToList(),
                CurrentPage = page,
                TotalPageCount = totalPageCount,
                Categories = categories,
                Brands = brands,
                Colors = colors,
                ProductCountPerPage = view,
                StartPoint = startPoint,
                EndPoint = endPoint,
                ProductCount = productCount
            };

            ViewBag.Order = order;

            return View(model);
        }
        public IActionResult Filter(int categoryId = 0, int brandId = 0, int colorId = 0, int page = 1, string order = "desc", int view = 4)
        {
            int productsPerPage = view;

            IQueryable<Product> allProducts = _dbContext.Products
                .Include(x => x.Images).ThenInclude(x => x.Image)
                .Include(x => x.Category)
                .Include(x => x.Brand)
                .Include(x => x.Colors).ThenInclude(x => x.Color);

            if (page <= 0) page = 1;

            if (categoryId == 0 && brandId == 0 && colorId == 0)
            {
                var products = allProducts
                    .Skip((page - 1) * productsPerPage)
                    .Take(productsPerPage)
                    .ToList();

                var model = new ShopIndexVM
                {
                    Products = products,
                };

                return View(model);
            }

            var sortedProducts = allProducts
               .Where(x => (x.CategoryId == categoryId)
               && (x.BrandId == brandId)
               && (x.Colors.FirstOrDefault().Id == colorId)
               ).ToList();

            var totalPageCount = (int)Math.Ceiling((double)allProducts.Count() / productsPerPage);

            var sortedModel = new ShopIndexVM
            {
                Products = sortedProducts,
                TotalPageCount = totalPageCount,
                CurrentPage = page
            };

            return View(sortedModel);
        }
        public IActionResult ProductDetails(int? id)
        {
            if (id is null) return NotFound();

            Product? product = _dbContext.Products
                .Include(x => x.Images).ThenInclude(x => x.Image)
                .FirstOrDefault(x => x.Id == id);

            if (product is null) return NotFound();

            var category = _dbContext.Categories.FirstOrDefault(x => x.Id == product.CategoryId);
            var brand = _dbContext.Brands.FirstOrDefault(x => x.Id == product.BrandId);

            ShopIndexVM model = new()
            {
                Product = product,
                CategoryName = category.Name,
                BrandName = category.Name,
            };

            return View(model);
        }
        public IActionResult Search(string? input)
        {
            var products = input == null ? new List<Product>()
                : _dbContext.Products
                .Where(x => x.Name.ToLower()
                .StartsWith(input.ToLower()))
                .ToList();

            return ViewComponent("SearchResult", products);
        }
    }
}

Backend_Project_Amado/Views/Shared/Components/SearchResult/SearchResultViewComponent.cs
using Backend_Project_Amado.Entities;
using Microsoft.AspNetCore.Mvc;

namespace Backend_Project_Amado.Views.Shared.Components.SearchResult
{
    public class SearchResultViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(List<Product> model)
        {
            return View(model);
        }
    }
}

Backend_Project_Amado/Views/Shared/Components/Subscriber/SubscriberViewComponent.cs
using Backend_Project_Amado.Data;
using Backend_Project_Amado.Entities;
using Backend_Project_Amado.Models;
using Microsoft.AspNetCore.Mvc;

namespace Backend_Project_Amado.Views.Shared.Components.Subscribers
{
    public class SubscriberViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            var model = new SubscribersComponentVM();
            return View(model);
        }
    }
}

Backend_Project_Amado/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <!-- Title  -->
    <title>Amado - Furniture Ecommerce Template</title>

    <!-- Favicon  -->
    <link rel="icon" href="~/img/core-img/favicon.ico">

    <!-- Core Style CSS -->
    <link rel="stylesheet" href="~/css/core-style.css">
    <link rel="stylesheet" href="~/style.css">
</head>
<body>
    <!-- Search Wrapper Area Start -->
    <div class="search-wrapper section-padding-100">
        <div class="search-close">
            <i class="fa fa-close" aria-hidden="true"></i>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="search-content">
                        <form asp-controller="Shop" asp-action="Search">
                            <input class="search-input" id="search" placeholder="Search...">
                            <button type="submit"><img src="img/core-img/search.png" alt=""></button>
                        </form>
                        <div class="search-result"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Search Wrapper Area End -->

    <!-- ##### Main Content Wrapper Start ##### -->
    <div class="main-content-wrapper d-flex clearfix" style="background-color:white">

        <!-- Mobile Nav (max width 767px)-->
        <div class="mobile-nav">
            <!-- Navbar Brand -->
            <div class="amado-navbar-brand">
                <a href="index.html"><img src="img/core-img/logo.png" alt=""></a>
            </div>
            <!-- Navbar Toggler -->
            <div class="amado-navbar-toggler">
                <span></span><span></span><span></span>
            </div>
        </div>

        <!-- Header Area Start -->
        <header class="header-area clearfix">
            <!-- Close Icon -->
            <div class="nav-close">
                <i class="fa fa-close" aria-hidden="true"></i>
            </div>
            <!-- Logo -->
            <div class="logo">
                <a href="index.html"><img src="img/core-img/logo.png" alt=""></a>
            </div>
            <!-- Amado Nav -->
            <nav class="amado-nav">
                <ul>
                    <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-controller="Shop" asp-action="Index">Shop</a></li>
                    <li><a asp-controller="Pages" asp-action="Cart">Cart</a></li>
                    <li class="active"><a asp-controller="Pages" asp-action="Checkout">Checkout</a></li>
                </ul>
            </nav>
            <!-- Button Group -->
            <div class="amado-btn-group mt-30 mb-100">
                <a href="#" class="btn amado-btn mb-15">%Discount%</a>
                <a href="#" class="btn amado-btn active">New this week</a>
            </div>
            <!-- Cart Menu -->
            <div class="cart-fav-search mb-100">
                <a asp-controller="Pages" asp-action="Cart" class="cart-nav"><img src="img/core-img/cart.png" alt=""> Cart <span>@ViewData["Count"]</span></a>
                <a href="#" class="fav-nav"><img src="img/core-img/favorites.png" alt=""> Favourite</a>
                <a href="#" class="search-nav"><img src="img/core-img/search.png" alt=""> Search</a>
            </div>
            <!-- Social Button -->
            <div class="social-info d-flex justify-content-between">
                <a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
                <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
            </div>
        </header>
        <!-- Header Area End -->

        @RenderBody()
    </div>
    <!-- ##### Main Content Wrapper End ##### -->

    @await Component.InvokeAsync("Subscriber")

    <!-- ##### Footer Area Start ##### -->
    <footer class="footer_area clearfix">
        <div class="container">
            <div class="row align-items-center">
                <!-- Single Widget Area -->
                <div class="col-12 col-lg-4">
                    <div class="single_widget_area">
                        <!-- Logo -->
                        <div class="footer-logo mr-50">
                            <a href="index.html"><img src="img/core-img/logo2.png" alt=""></a>
                        </div>
                        <!-- Copywrite Text -->
                        <p class="copywrite">
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a> & Re-distributed by <a href="https://themewagon.com/" target="_blank">Themewagon</a>
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        </p>
                    </div>
                </div>
                <!-- Single Widget Area -->
                <div class="col-12 col-lg-8">
                    <div class="single_widget_area">
                        <!-- Footer Menu -->
                        <div class="footer_menu">
                            <nav class="navbar navbar-expand-lg justify-content-end">
                                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#footerNavContent" aria-controls="footerNavContent" aria-expanded="false" aria-label="Toggle navigation"><i class="fa fa-bars"></i></button>
                                <div class="collapse navbar-collapse" id="footerNavContent">
                                    <ul class="navbar-nav ml-auto">
                                        <li class="nav-item active">
                                            <a class="nav-link" href="index.html">Home</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="shop.html">Shop</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="product-details.html">Product</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="cart.html">Cart</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="checkout.html">Checkout</a>
                                        </li>
                                    </ul>
                                </div>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- ##### Footer Area End ##### -->
    
    <!-- ##### jQuery (Necessary for All JavaScript Plugins) ##### -->
    <script src="~/js/jquery/jquery-2.2.4.min.js"></script>
    <!-- Popper js -->
    <script src="~/js/popper.min.js"></script>
    <!-- Bootstrap js -->
    <script src="~/js/bootstrap.min.js"></script>
    <!-- Plugins js -->
    <script src="~/js/plugins.js"></script>
    <!-- Active js -->
    <script src="~/js/active.js"></script>
    <script src="~/js/Search.js"></script>
    @RenderSection("Scripts", false)
</body>
</html>